package com.findupto.voicepos
import androidx.compose.foundation.clickable
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
private fun RangeChips(selected:Int,set:(Int)->Unit){Row(Modifier.horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(6.dp)){listOf("Today","7 Days","30 Days","All").forEachIndexed{i,t->FilterChip(selected==i,{set(i)},label={Text(t)})}}}
@Composable fun EnhancedMenuPage(menu:List<MenuItem>,store:Store,refresh:()->Unit,scan:()->Unit,addToCart:(MenuItem)->Unit){var edit by remember{mutableStateOf<MenuItem?>(null)};var add by remember{mutableStateOf(false)};Column(Modifier.fillMaxSize().padding(16.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(6.dp)){Button({add=true},Modifier.weight(1f)){Text("ADD PRODUCT")};OutlinedButton(scan,Modifier.weight(1f)){Text("SCAN")}};Text("Tap product to add. Edit, delete or change price anytime.",style=MaterialTheme.typography.bodySmall);LazyColumn{items(menu,key={it.id}){m->Card(Modifier.fillMaxWidth().padding(vertical=3.dp)){Row(Modifier.padding(10.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f).clickable{addToCart(m)}){Text(m.name,fontWeight=FontWeight.SemiBold);Text(listOf(m.variant,m.size).filter(String::isNotBlank).joinToString(" • "));Text(money(m.price))};TextButton({edit=m}){Text("EDIT")};TextButton({store.removeMenuItem(m.id);refresh()}){Text("DELETE")}}}}}};if(add)ProductEditor(null,{store.addMenuItem(it);add=false;refresh()}){add=false};edit?.let{ProductEditor(it,{store.updateMenuItem(it);edit=null;refresh()}){edit=null}}}
@Composable private fun ProductEditor(item:MenuItem?,save:(MenuItem)->Unit,close:()->Unit){var n by remember(item){mutableStateOf(item?.name?:"")};var v by remember(item){mutableStateOf(item?.variant?:"")};var s by remember(item){mutableStateOf(item?.size?:"")};var p by remember(item){mutableStateOf(item?.price?.toString() ?: "")};AlertDialog(onDismissRequest=close,title={Text(if(item==null)"Add Product" else "Edit Product")},text={Column(verticalArrangement=Arrangement.spacedBy(6.dp)){OutlinedTextField(n,{n=it},label={Text("Product")},singleLine=true);OutlinedTextField(v,{v=it},label={Text("Variant")},singleLine=true);OutlinedTextField(s,{s=it},label={Text("Size")},singleLine=true);OutlinedTextField(p,{p=it},label={Text("Price")},singleLine=true)}},confirmButton={TextButton(onClick={val price=p.toDoubleOrNull();if(n.isNotBlank()&&price!=null)save(item?.copy(name=n.trim(),variant=v.trim(),size=s.trim(),price=price)?:MenuItem(System.currentTimeMillis(),n.trim(),price,v.trim(),s.trim()))}){Text("SAVE")}},dismissButton={TextButton(onClick=close){Text("CANCEL")}})}
@Composable fun EnhancedExpensesPage(expenses:List<Expense>,add:()->Unit,profile:CompanyProfile,printer:PrinterManager,theme:ReceiptTheme,store:Store,refresh:()->Unit){var range by remember{mutableIntStateOf(0)};var selected by remember{mutableStateOf<Expense?>(null)};val shown=expenses.filter{inRange(it.time,range)}.sortedByDescending{it.time};Column(Modifier.fillMaxSize().padding(16.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Text("Expenses",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Spacer(Modifier.weight(1f));Button(add){Text("ADD")}};RangeChips(range){range=it};Text("${shown.size} records • ${money(shown.sumOf{it.amount})}",fontWeight=FontWeight.Bold);LazyColumn{items(shown,key={it.id}){e->Card(Modifier.fillMaxWidth().padding(vertical=3.dp).clickable{selected=e}){ListItem(headlineContent={Text(e.title,fontWeight=FontWeight.SemiBold)},supportingContent={Text("${e.category} • ${date(e.time)}")},trailingContent={Text(money(e.amount),fontWeight=FontWeight.Bold)})}}}};selected?.let{e->AlertDialog(onDismissRequest={selected=null},title={Text("Expense #${e.id}")},text={Column{Text(e.title,fontWeight=FontWeight.Bold);Text(e.category);Text(date(e.time));Text(money(e.amount),style=MaterialTheme.typography.headlineSmall)}},confirmButton={TextButton({printer.printCustomer(expenseReceipt(e,profile,theme))}){Text("PRINT")}},dismissButton={TextButton({store.removeExpense(e.id);selected=null;refresh()}){Text("DELETE")}})}}
@Composable fun EnhancedSalesPage(sales:List<Sale>,open:(Sale)->Unit){var range by remember{mutableIntStateOf(0)};var q by remember{mutableStateOf("")};val shown=sales.filter{inRange(it.time,range)}.filter{q.isBlank()||it.id.toString().contains(q)||it.customerName.contains(q,true)||it.customerPhone.contains(q,true)}.sortedByDescending{it.time};Column(Modifier.fillMaxSize().padding(16.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text("Sales History",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Text(money(shown.sumOf{it.total}),fontWeight=FontWeight.Bold)};OutlinedTextField(q,{q=it},Modifier.fillMaxWidth(),label={Text("Receipt / customer / phone")},singleLine=true);RangeChips(range){range=it};LazyColumn{items(shown,key={it.id}){s->Card(Modifier.fillMaxWidth().padding(vertical=3.dp).clickable{open(s)}){ListItem(headlineContent={Text("Receipt #${s.id}",fontWeight=FontWeight.Bold)},supportingContent={Text(listOf(s.customerName,s.customerPhone).filter(String::isNotBlank).joinToString(" • ")+"\n"+date(s.time))},trailingContent={Text(money(s.total),fontWeight=FontWeight.Bold)})}}}}}
@Composable fun EnhancedAnalytics(sales:List<Sale>,expenses:List<Expense>,cash:Double){var range by remember{mutableIntStateOf(0)};val ss=sales.filter{inRange(it.time,range)};val es=expenses.filter{inRange(it.time,range)};val sv=ss.sumOf{it.total};val ev=es.sumOf{it.amount};Column(Modifier.fillMaxSize().padding(16.dp).verticalScroll(rememberScrollState()),verticalArrangement=Arrangement.spacedBy(6.dp)){Text("Business Analysis",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);RangeChips(range){range=it};Text("${ss.size} sales • ${es.size} expenses",style=MaterialTheme.typography.bodySmall);Stat("Sales",sv);Stat("Expenses",ev);Stat("Net",sv-ev);Stat("Cash",cash);HorizontalDivider();Text("Top Products",fontWeight=FontWeight.Bold);ss.flatMap{it.items}.groupBy{it.name}.mapValues{it.value.sumOf{x->x.qty}}.entries.sortedByDescending{it.value}.take(10).forEach{Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text(it.key);Text("${it.value} sold")}}}}
@Composable private fun Stat(name:String,value:Double){Card(Modifier.fillMaxWidth()){Row(Modifier.padding(12.dp),horizontalArrangement=Arrangement.SpaceBetween){Text(name,fontWeight=FontWeight.SemiBold);Text(money(value),fontWeight=FontWeight.Bold)}}}
