package com.findupto.voicepos
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
@Composable fun VoicePosTheme(content:@Composable ()->Unit){MaterialTheme(colorScheme=darkColorScheme(primary=Color(0xFF9B8CFF),secondary=Color(0xFF42D6A4)),content=content)}
@OptIn(ExperimentalMaterial3Api::class)
@Composable fun PosApp(store:Store,printer:PrinterManager,heard:String,voiceStatus:String,clearHeard:()->Unit,listen:()->Unit,openSpeechSettings:()->Unit,exportMenu:()->Unit,importMenu:()->Unit,pickLogo:()->Unit,scanDocument:()->Unit,exportBackup:()->Unit,importBackup:()->Unit){
 var tab by remember{mutableIntStateOf(0)};var cart by remember{mutableStateOf(emptyList<SaleItem>())};var cash by remember{mutableStateOf(store.cash())};var tick by remember{mutableIntStateOf(0)};var editing by remember{mutableStateOf<PendingSale?>(null)};var amend by remember{mutableStateOf<PendingSale?>(null)};var settings by remember{mutableStateOf(false)};var printerSettings by remember{mutableStateOf(false)};var businessSettings by remember{mutableStateOf(false)};var expense by remember{mutableStateOf(false)};var opening by remember{mutableStateOf(!store.hasOpeningCash())};var selectedSale by remember{mutableStateOf<Sale?>(null)};var manualCart by remember{mutableStateOf(false)};var discountDialog by remember{mutableStateOf(false)};var customerDialog by remember{mutableStateOf(false)};var customerName by remember{mutableStateOf("")};var customerPhone by remember{mutableStateOf("")};var orderType by remember{mutableStateOf("DINE_IN")};var customerAddress by remember{mutableStateOf("")};var ultra by remember{mutableStateOf(false)};var settlementOrder by remember{mutableStateOf<PendingSale?>(null)}
 val menu=remember(tick){store.menu()};val profile=remember(tick){store.profile()};val sales=remember(tick){store.sales()};val expenses=remember(tick){store.expenses()};val pending=remember(tick){store.pending()}
 fun addToCart(item:SaleItem){val i=cart.indexOfFirst{it.name.equals(item.name,true)&&it.price==item.price};cart=if(i>=0)cart.toMutableList().also{it[i]=it[i].copy(qty=it[i].qty+item.qty)}else cart+item}
 fun applyCartDiscount(amount:Double){val products=cart.filterNot{it.name.startsWith(CART_DISCOUNT_PREFIX)};cart=if(amount>0)products+SaleItem(CART_DISCOUNT_PREFIX,1,-amount)else products}
 fun requestSettle(order:PendingSale){settlementOrder=order}
 fun finalizeSale(order:PendingSale,method:String,paid:Double,due:Double){val subtotal=order.total;val service=store.serviceCharge(subtotal);val tax=store.tax(subtotal);val total=subtotal+service+tax;val shift=store.activeShift()?.id?:0L;val sale=Sale(order.id,order.items,total,System.currentTimeMillis(),order.customerName,order.customerPhone,order.orderType,order.customerAddress,method,paid,due,shift,service,tax,cartDiscount(order.items));store.addSale(sale);if(method=="CASH"&&paid>0){cash+=paid;store.setCash(cash)};store.removePending(order.id);printer.printCustomer(customerReceipt(sale,profile,store.theme()));settlementOrder=null;tick++}
 LaunchedEffect(heard){if(heard.isNotBlank()){VoiceCommandEngine.parse(heard,menu).forEach{command->when(command){is VoiceCommand.Add->addToCart(command.item);is VoiceCommand.MenuAdd->{store.addMenuItem(command.item);tick++};is VoiceCommand.MenuPrice->{menu.firstOrNull{it.name.equals(command.name,true)||it.name.contains(command.name,true)||VoiceCommandEngine.parse(command.name,menu).filterIsInstance<VoiceCommand.Add>().firstOrNull()?.item?.name==it.name}?.let{store.updateMenuItem(it.copy(price=command.price));tick++}};is VoiceCommand.MenuRemove->{menu.firstOrNull{it.name.equals(command.name,true)||it.name.contains(command.name,true)}?.let{store.removeMenuItem(it.id);tick++}};VoiceCommand.Clear,VoiceCommand.NewOrder->cart=emptyList();VoiceCommand.Sales->tab=3;VoiceCommand.Expenses->tab=4;VoiceCommand.Reports,VoiceCommand.Analytics->tab=5;VoiceCommand.Settings->settings=true;VoiceCommand.Menu->tab=1;VoiceCommand.Kitchen->tab=2;is VoiceCommand.PayLast->pending.lastOrNull()?.let(::requestSettle);is VoiceCommand.Quantity->cart=cart.map{if(it.name.contains(command.name,true))it.copy(qty=(it.qty+command.delta).coerceAtLeast(0))else it}.filter{it.qty>0};is VoiceCommand.Remove->cart=cart.filterNot{it.name.contains(command.name,true)};VoiceCommand.CompletePrint->if(cart.isNotEmpty()){val order=PendingSale(System.currentTimeMillis(),cart,System.currentTimeMillis(),customerName,customerPhone,orderType,customerAddress);store.addPending(order);printer.printKitchen(kitchenReceipt(order,profile,store.theme()));cart=emptyList();tick++};VoiceCommand.Complete->Unit}}};clearHeard()}
 fun sendOrder(){if(cart.isNotEmpty())customerDialog=true}
 fun saveCustomer(name:String,phone:String,type:String,address:String){customerName=name.trim();customerPhone=phone.trim();orderType=type;customerAddress=address.trim();val order=PendingSale(System.currentTimeMillis(),cart,System.currentTimeMillis(),customerName,customerPhone,orderType,customerAddress);store.addPending(order);printer.printKitchen(kitchenReceipt(order,profile,store.theme()));cart=emptyList();tick++}
 Scaffold(topBar={CenterAlignedTopAppBar(title={Column(horizontalAlignment=Alignment.CenterHorizontally){Text(profile.name,fontWeight=FontWeight.Bold);Text("PREMIUM POS",style=MaterialTheme.typography.labelSmall)}},actions={IconButton(onClick={ultra=true}){Icon(Icons.Default.AutoAwesome,"Ultra Control Center")};IconButton(onClick={printerSettings=true}){Icon(Icons.Default.Print,"Printer settings")};IconButton(onClick={businessSettings=true}){Icon(Icons.Default.Payments,"Tax, currency & service")};IconButton(onClick={settings=true}){Icon(Icons.Default.Settings,"Settings")}})},bottomBar={NavigationBar{val names=listOf("Sale","Menu","Kitchen","Sales","Expenses","Analytics");val icons=listOf(Icons.Default.PointOfSale,Icons.Default.MenuBook,Icons.Default.Restaurant,Icons.Default.ReceiptLong,Icons.Default.Payments,Icons.Default.Insights);names.forEachIndexed{index,name->NavigationBarItem(selected=tab==index,onClick={tab=index},icon={Icon(icons[index],name)},label={Text(name)})}}},floatingActionButton={ExtendedFloatingActionButton(onClick=listen,icon={Icon(Icons.Default.Mic,"Voice")},text={Text("VOICE")},shape=CircleShape)}){padding->Box(Modifier.fillMaxSize().padding(padding)){when(tab){0->PremiumQuickSale(cart,voiceStatus,::sendOrder,listen,openSpeechSettings,{cart=emptyList()},{manualCart=true},{discountDialog=true}){item,delta->cart=cart.map{if(it==item)it.copy(qty=(it.qty+delta).coerceAtLeast(0))else it}.filter{it.qty>0}};1->EnhancedMenuPage(menu,store,{tick++},scanDocument){addToCart(SaleItem(it.name,1,it.price));tab=0};2->KitchenQueue(pending,profile,printer,{requestSettle(it)}){amend=it};3->EnhancedSalesPage(sales){selectedSale=it};4->EnhancedExpensesPage(expenses,{expense=true},profile,printer,store.theme(),store){tick++};5->EnhancedAnalytics(sales,expenses,cash)}}}
 if(opening)OpeningCash{cash=it;store.setOpeningCash(it);opening=false};if(expense)ExpenseDialog{name,category,amount->store.addExpense(Expense(System.currentTimeMillis(),name,category,amount,System.currentTimeMillis(),"CASH",store.activeShift()?.id?:0L));cash-=amount;store.setCash(cash);tick++;expense=false};if(settings)SettingsPage(store,printer,pickLogo,exportBackup,importBackup){settings=false;tick++};if(printerSettings)PrinterSettingsDialog(store,printer){printerSettings=false};if(businessSettings)BusinessSettingsDialog(store){businessSettings=false;tick++};if(customerDialog)CustomerDetailsDialog({name,phone,type,address->saveCustomer(name,phone,type,address);customerDialog=false},{customerDialog=false});editing?.let{order->EditDialog(order,{updated->store.replacePending(updated);editing=null;tick++},{editing=null})};amend?.let{order->AmendPendingOrderDialog(order,menu,{updated->store.replacePending(updated);printer.printKitchen(kitchenReceipt(updated,profile,store.theme()));amend=null;tick++},{amend=null})};selectedSale?.let{sale->SaleDetailDialog(sale,profile,printer,store.theme()){selectedSale=null}};if(manualCart)MultiAddCartDialog(menu,{items->items.forEach{item,qty->addToCart(SaleItem(item.name,qty,item.price))}},{manualCart=false});if(discountDialog)DiscountDialog(cartProductSubtotal(cart),cartDiscount(cart),::applyCartDiscount){discountDialog=false};if(ultra)UltraControlCenter(store){ultra=false;tick++};settlementOrder?.let{order->SettlementDialog(order,store.totalWithTax(order.total),{method,paid,due->finalizeSale(order,method,paid,due)},{settlementOrder=null})}
}
