package com.findupto.voicepos

import androidx.compose.foundation.clickable
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.graphics.vector.ImageVector

@Composable private fun AddMenuDialog(save:(String,String,String,Double)->Unit,close:()->Unit){var name by remember{mutableStateOf("")};var variant by remember{mutableStateOf("")};var size by remember{mutableStateOf("")};var price by remember{mutableStateOf("")};AlertDialog(onDismissRequest=close,title={Text("Add Product / Variant / Size")},text={Column(Modifier.verticalScroll(rememberScrollState()),verticalArrangement=Arrangement.spacedBy(8.dp)){OutlinedTextField(name,{name=it},label={Text("Product name")});OutlinedTextField(variant,{variant=it},label={Text("Variant")});OutlinedTextField(size,{size=it},label={Text("Size")});OutlinedTextField(price,{price=it},label={Text("Price")})}},confirmButton={TextButton(onClick={price.toDoubleOrNull()?.takeIf{it>0}?.let{if(name.isNotBlank())save(name,variant,size,it)}}){Text("Save")}},dismissButton={TextButton(onClick=close){Text("Cancel")}})}
@Composable private fun KitchenQueue(queue:List<PendingSale>,profile:CompanyProfile,printer:PrinterManager,pay:(PendingSale)->Unit,edit:(PendingSale)->Unit){Column(Modifier.fillMaxSize().padding(16.dp)){Row(Modifier.fillMaxWidth(),Arrangement.SpaceBetween,Alignment.CenterVertically){Column{Text("Kitchen Queue",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Text(queue.size.toString()+" unpaid orders")};Button(onClick={queue.forEach{printer.printKitchen(kitchenReceipt(it,profile,ReceiptTheme.MODERN))}},enabled=queue.isNotEmpty()){Text("Print all")}};LazyColumn{items(queue){order->Card(Modifier.fillMaxWidth().padding(vertical=5.dp).clickable{edit(order)}){Row(Modifier.padding(14.dp),verticalAlignment=Alignment.CenterVertically){Icon(Icons.Default.Restaurant,null);Column(Modifier.weight(1f).padding(horizontal=10.dp)){Text("#"+order.id,fontWeight=FontWeight.Bold);Text(order.items.joinToString(", "){it.qty.toString()+"× "+it.name});Text(money(order.total))};TextButton(onClick={pay(order)}){Text("PAY & PRINT")}}}}}}}
@Composable private fun EditDialog(order:PendingSale,save:(PendingSale)->Unit,close:()->Unit){var items by remember{mutableStateOf(order.items)};var name by remember{mutableStateOf("")};var price by remember{mutableStateOf("")};AlertDialog(onDismissRequest=close,title={Text("Edit order #"+order.id)},text={Column(Modifier.verticalScroll(rememberScrollState())){items.forEach{item->Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(item.name);Text(item.qty.toString()+" × "+money(item.price),style=MaterialTheme.typography.bodySmall)};IconButton(onClick={items=items.map{x->if(x==item)x.copy(qty=x.qty-1)else x}.filter{it.qty>0}}){Icon(Icons.Default.Remove,null)}}};HorizontalDivider();OutlinedTextField(name,{name=it},label={Text("Add item")});OutlinedTextField(price,{price=it},label={Text("Price")})}},confirmButton={TextButton(onClick={val v=price.toDoubleOrNull();save(order.copy(items=if(name.isNotBlank()&&v!=null)items+SaleItem(name,1,v)else items))}){Text("Save")}},dismissButton={TextButton(onClick=close){Text("Cancel")}})}
@Composable private fun SalesPage(sales:List<Sale>,filter:Int,setFilter:(Int)->Unit,open:(Sale)->Unit){Column(Modifier.fillMaxSize().padding(16.dp)){Text("Paid Sales",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);FilterRow(filter,setFilter);if(sales.isEmpty())EmptyState(Icons.Default.ReceiptLong,"No sales","Completed receipts will appear here.");LazyColumn{items(sales.reversed()){sale->Card(Modifier.fillMaxWidth().padding(vertical=4.dp).clickable{open(sale)}){Row(Modifier.padding(14.dp),verticalAlignment=Alignment.CenterVertically){Icon(Icons.Default.ReceiptLong,null);Column(Modifier.weight(1f).padding(horizontal=12.dp)){Text("Receipt #"+sale.id,fontWeight=FontWeight.Bold);Text(sale.items.sumOf{it.qty}.toString()+" items • "+date(sale.time),style=MaterialTheme.typography.bodySmall);Text(money(sale.total),fontWeight=FontWeight.Bold)};TextButton(onClick={open(sale)}){Text("DETAILS")}}}}}}}
@Composable private fun SaleDetailDialog(sale:Sale,profile:CompanyProfile,printer:PrinterManager,theme:ReceiptTheme,close:()->Unit){AlertDialog(onDismissRequest=close,title={Text("Receipt #"+sale.id)},text={Column(Modifier.verticalScroll(rememberScrollState()),verticalArrangement=Arrangement.spacedBy(8.dp)){Text(date(sale.time),style=MaterialTheme.typography.bodySmall);sale.items.forEach{item->Row(Modifier.fillMaxWidth(),Arrangement.SpaceBetween){Column(Modifier.weight(1f)){Text(item.name,fontWeight=FontWeight.SemiBold);Text(item.qty.toString()+" × "+money(item.price),style=MaterialTheme.typography.bodySmall)};Text(money(item.total),fontWeight=FontWeight.SemiBold)}};HorizontalDivider();Row(Modifier.fillMaxWidth(),Arrangement.SpaceBetween){Text("TOTAL",fontWeight=FontWeight.Bold);Text(money(sale.total),fontWeight=FontWeight.Bold)}}},confirmButton={TextButton(onClick={printer.printCustomer(customerReceipt(sale,profile,theme))}){Text("RE-PRINT")}},dismissButton={TextButton(onClick=close){Text("Close")}})}
@Composable private fun CustomerDetailsDialog(done:(String,String)->Unit,close:()->Unit){var name by remember{mutableStateOf("")};var phone by remember{mutableStateOf("")};AlertDialog(onDismissRequest=close,title={Text("Customer Details (Optional)")},text={Column(verticalArrangement=Arrangement.spacedBy(8.dp)){OutlinedTextField(name,{name=it},label={Text("Customer Name")},singleLine=true);OutlinedTextField(phone,{phone=it},label={Text("Phone Number")},singleLine=true)}},confirmButton={TextButton(onClick={done(name,phone)}){Text("PRINT KITCHEN")}},dismissButton={TextButton(onClick=close){Text("Skip Details")}})}
@Composable private fun ExpensesPage(expenses:List<Expense>,filter:Int,setFilter:(Int)->Unit,add:()->Unit){Column(Modifier.fillMaxSize().padding(16.dp)){Row(Modifier.fillMaxWidth(),Arrangement.SpaceBetween,Alignment.CenterVertically){Text("Expenses",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Button(onClick=add){Text("Add")}};FilterRow(filter,setFilter);if(expenses.isEmpty())EmptyState(Icons.Default.Payments,"No expenses","Track shop expenses here.");LazyColumn{items(expenses.reversed()){ListItem(headlineContent={Text(it.title)},supportingContent={Text(it.category+" • "+date(it.time))},trailingContent={Text(money(it.amount),fontWeight=FontWeight.Bold)})}}}}
@Composable private fun FilterRow(filter:Int,setFilter:(Int)->Unit){Row(Modifier.horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(5.dp)){listOf("Today","7 days","30 days","All").forEachIndexed{i,n->FilterChip(filter==i,{setFilter(i)},label={Text(n)})}}}
@Composable private fun Analytics(sales:List<Sale>,expenses:List<Expense>,cash:Double,filter:Int,setFilter:(Int)->Unit){val sv=sales.sumOf{it.total};val ev=expenses.sumOf{it.amount};Column(Modifier.fillMaxSize().padding(16.dp).verticalScroll(rememberScrollState())){Text("Analytics",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);FilterRow(filter,setFilter);Metric("Sales",sv,Icons.Default.TrendingUp);Metric("Expenses",ev,Icons.Default.TrendingDown);Metric("Cash",cash,Icons.Default.AccountBalanceWallet);Metric("Net",sv-ev,Icons.Default.AccountBalance)}}
@Composable private fun Metric(title:String,value:Double,icon:ImageVector){Card(Modifier.fillMaxWidth().padding(vertical=5.dp)){Row(Modifier.padding(16.dp),verticalAlignment=Alignment.CenterVertically){Icon(icon,null);Spacer(Modifier.width(12.dp));Text(title,Modifier.weight(1f));Text(money(value),fontWeight=FontWeight.Bold)}}}
@Composable private fun EmptyState(icon:ImageVector,title:String,body:String){Column(Modifier.fillMaxWidth().padding(24.dp),horizontalAlignment=Alignment.CenterHorizontally){Icon(icon,null,Modifier.size(40.dp));Text(title,fontWeight=FontWeight.Bold);Text(body,color=MaterialTheme.colorScheme.onSurfaceVariant)}}
@Composable private fun OpeningCash(done:(Double)->Unit){var value by remember{mutableStateOf("")};AlertDialog(onDismissRequest={},title={Text("Opening Cash")},text={OutlinedTextField(value,{value=it},label={Text("Cash in hand")})},confirmButton={TextButton(onClick={done(value.toDoubleOrNull()?:0.0)}){Text("Continue")}})}
@Composable private fun ExpenseDialog(done:(String,String,Double)->Unit){var name by remember{mutableStateOf("")};var category by remember{mutableStateOf("")};var amount by remember{mutableStateOf("")};AlertDialog(onDismissRequest={},title={Text("Add Expense")},text={Column{OutlinedTextField(name,{name=it},label={Text("Description")});OutlinedTextField(category,{category=it},label={Text("Category")});OutlinedTextField(amount,{amount=it},label={Text("Amount")})}},confirmButton={TextButton(onClick={amount.toDoubleOrNull()?.let{done(name,category,it)}}){Text("Save")}},dismissButton={TextButton(onClick={}){Text("Close")}})}
