package com.findupto.voicepos

import androidx.compose.foundation.clickable
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.graphics.vector.ImageVector

@Composable
fun VoicePosTheme(content: @Composable () -> Unit) { MaterialTheme(colorScheme=darkColorScheme(primary=androidx.compose.ui.graphics.Color(0xFF9B8CFF),secondary=androidx.compose.ui.graphics.Color(0xFF42D6A4)),content=content) }

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun PosApp(store:Store,printer:PrinterManager,heard:String,voiceStatus:String,clearHeard:()->Unit,listen:()->Unit,openSpeechSettings:()->Unit,exportMenu:()->Unit,importMenu:()->Unit,pickLogo:()->Unit,scanDocument:()->Unit,exportBackup:()->Unit,importBackup:()->Unit){
 var tab by remember{mutableIntStateOf(0)};var cart by remember{mutableStateOf(emptyList<SaleItem>())};var cash by remember{mutableStateOf(store.cash())};var tick by remember{mutableIntStateOf(0)};var filter by remember{mutableIntStateOf(0)};var editing by remember{mutableStateOf<PendingSale?>(null)};var settings by remember{mutableStateOf(false)};var expense by remember{mutableStateOf(false)};var opening by remember{mutableStateOf(!store.hasOpeningCash())};var selectedSale by remember{mutableStateOf<Sale?>(null)};var manualCart by remember{mutableStateOf(false)};var customerDialog by remember{mutableStateOf(false)};var customerName by remember{mutableStateOf("")};var customerPhone by remember{mutableStateOf("")}
 val menu=remember(tick){store.menu()};val profile=remember(tick){store.profile()};val sales=remember(tick){store.sales()};val expenses=remember(tick){store.expenses()};val pending=remember(tick){store.pending()}
 LaunchedEffect(heard){if(heard.isNotBlank()){VoiceCommandEngine.parse(heard,menu).forEach{command->when(command){is VoiceCommand.Add->{val i=cart.indexOfFirst{it.name.equals(command.item.name,true)&&it.price==command.item.price};cart=if(i>=0)cart.toMutableList().also{l->l[i]=l[i].copy(qty=l[i].qty+command.item.qty)}else cart+command.item};VoiceCommand.Clear->cart=emptyList();VoiceCommand.Sales->tab=3;VoiceCommand.Expenses->tab=4;VoiceCommand.Reports,VoiceCommand.Analytics->tab=5;VoiceCommand.Settings->settings=true;VoiceCommand.Menu->tab=1;VoiceCommand.Kitchen->tab=2;VoiceCommand.NewOrder->cart=emptyList();is VoiceCommand.PayLast->pending.lastOrNull()?.let{pay(it)};is VoiceCommand.Quantity->{cart=cart.map{if(it.name.contains(command.name,true))it.copy(qty=(it.qty+command.delta).coerceAtLeast(0))else it}.filter{it.qty>0}};is VoiceCommand.Remove->cart=cart.filterNot{it.name.contains(command.name,true)};VoiceCommand.CompletePrint->{if(cart.isNotEmpty()){val order=PendingSale(System.currentTimeMillis(),cart,System.currentTimeMillis(),customerName.trim(),customerPhone.trim());store.addPending(order);printer.printKitchen(kitchenReceipt(order,profile,store.theme()));cart=emptyList();customerName="";customerPhone="";tick++}};VoiceCommand.Complete->Unit}};clearHeard()}}
 fun sendOrder(){if(cart.isNotEmpty())customerDialog=true}
 fun sendOrderWithCustomer(name:String,phone:String){customerName=name.trim();customerPhone=phone.trim();val order=PendingSale(System.currentTimeMillis(),cart,System.currentTimeMillis(),customerName,customerPhone);store.addPending(order);printer.printKitchen(kitchenReceipt(order,profile,store.theme()));cart=emptyList();tick++}
 fun pay(order:PendingSale){val sale=Sale(order.id,order.items,order.total,System.currentTimeMillis(),order.customerName,order.customerPhone);store.addSale(sale);cash+=sale.total;store.setCash(cash);store.removePending(order.id);printer.printCustomer(customerReceipt(sale,profile,store.theme()));tick++}
 Scaffold(topBar={CenterAlignedTopAppBar(title={Column(horizontalAlignment=Alignment.CenterHorizontally){Text(profile.name.ifBlank{"The Slice of Heaven"},fontWeight=FontWeight.Bold);Text("VOICE POS • PREMIUM",style=MaterialTheme.typography.labelSmall,color=MaterialTheme.colorScheme.secondary)}},actions={IconButton(onClick={settings=true}){Icon(Icons.Default.Settings,"Settings")}}},bottomBar={NavigationBar{val names=listOf("Sale","Menu","Kitchen","Sales","Expenses","Analytics");val icons=listOf(Icons.Default.PointOfSale,Icons.Default.MenuBook,Icons.Default.Restaurant,Icons.Default.ReceiptLong,Icons.Default.Payments,Icons.Default.Insights);names.forEachIndexed{i,n->NavigationBarItem(tab==i,{tab=i},icon={Icon(icons[i],n)},label={Text(n)})}}},floatingActionButton={ExtendedFloatingActionButton(onClick=listen,icon={Icon(Icons.Default.Mic,"Voice")},text={Text("VOICE")},shape=CircleShape)}){padding->Box(Modifier.fillMaxSize().padding(padding)){when(tab){0->QuickSale(cart,voiceStatus,::sendOrder,listen,openSpeechSettings,{cart=emptyList()},{manualCart=true}){item,delta->cart=cart.map{if(it==item)it.copy(qty=(it.qty+delta).coerceAtLeast(0))else it}.filter{it.qty>0}};1->MenuPage(menu,store,tick=tick,refresh={tick++},exportMenu=exportMenu,importMenu=importMenu,scanDocument=scanDocument){item->val i=cart.indexOfFirst{it.name.equals(item.name,true)&&it.price==item.price};cart=if(i>=0)cart.toMutableList().also{l->l[i]=l[i].copy(qty=l[i].qty+1)}else cart+SaleItem(item.name,1,item.price);tab=0};2->KitchenQueue(pending,profile,printer,::pay){editing=it};3->SalesPage(sales.filter{inRange(it.time,filter)},filter,{filter=it},{selectedSale=it});4->ExpensesPage(expenses.filter{inRange(it.time,filter)},filter,{filter=it}){expense=true};5->Analytics(sales.filter{inRange(it.time,filter)},expenses.filter{inRange(it.time,filter)},cash,filter,{filter=it})}}}}
 if(opening)OpeningCash{cash=it;store.setOpeningCash(it);opening=false};if(expense)ExpenseDialog{name,category,amount->store.addExpense(Expense(System.currentTimeMillis(),name,category,amount,System.currentTimeMillis()));cash-=amount;store.setCash(cash);tick++;expense=false};if(settings)SettingsPage(store,printer,pickLogo,exportBackup,importBackup){settings=false;tick++};if(customerDialog)CustomerDetailsDialog({name,phone->sendOrderWithCustomer(name,phone);customerDialog=false},{customerDialog=false});editing?.let{order->EditDialog(order,{updated->store.replacePending(updated);editing=null;tick++},{editing=null})};selectedSale?.let{sale->SaleDetailDialog(sale,profile,printer,store.theme()){selectedSale=null}};if(manualCart)ManualCartDialog(menu,cart,{item->{val i=cart.indexOfFirst{it.name.equals(item.name,true)&&it.price==item.price};cart=if(i>=0)cart.toMutableList().also{l->l[i]=l[i].copy(qty=l[i].qty+1)}else cart+SaleItem(item.name,1,item.price)}},{name,qty,price->{val i=cart.indexOfFirst{it.name.equals(name,true)&&it.price==price};cart=if(i>=0)cart.toMutableList().also{l->l[i]=l[i].copy(qty=l[i].qty+qty)}else cart+SaleItem(name,qty,price)}},{manualCart=false})
}
