package com.findupto.voicepos

import androidx.compose.foundation.clickable
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp

@Composable
fun QuickSale(cart:List<SaleItem>,voiceStatus:String,send:()->Unit,listen:()->Unit,openSpeechSettings:()->Unit,clear:()->Unit,manual:()->Unit,changeQty:(SaleItem,Int)->Unit){Column(Modifier.fillMaxSize().padding(16.dp).verticalScroll(rememberScrollState()),verticalArrangement=Arrangement.spacedBy(12.dp)){Card(Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Row(verticalAlignment=Alignment.CenterVertically){Icon(Icons.Default.Mic,null);Spacer(Modifier.width(8.dp));Column(Modifier.weight(1f)){Text("Power Voice",fontWeight=FontWeight.Bold);Text(voiceStatus,style=MaterialTheme.typography.bodySmall)};IconButton(onClick=listen){Icon(Icons.Default.MicNone,"Listen")}};Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(8.dp)){Button(onClick=manual,Modifier.weight(1f)){Text("MANUAL ADD")};OutlinedButton(onClick=listen,Modifier.weight(1f)){Text("VOICE")}};if(voiceStatus.contains("error",true)||voiceStatus.contains("unavailable",true))OutlinedButton(onClick=openSpeechSettings,Modifier.fillMaxWidth()){Text("Check speech language / settings")};Text("Try: two shawarma price 200 • change shawarma price 250 • add pizza to menu at 700",style=MaterialTheme.typography.bodySmall)}};Card(Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text("Current Order",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold);if(cart.isNotEmpty())TextButton(onClick=clear){Text("Clear")}};if(cart.isEmpty())EmptyState(Icons.Default.ShoppingCart,"No items","Use voice or manual add");cart.forEach{item->Row(Modifier.fillMaxWidth().padding(vertical=6.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(item.name,fontWeight=FontWeight.SemiBold);Text("${item.qty} × ${money(item.price)}",style=MaterialTheme.typography.bodySmall)};IconButton(onClick={changeQty(item,-1)}){Icon(Icons.Default.Remove,null)};Text(money(item.total));IconButton(onClick={changeQty(item,1)}){Icon(Icons.Default.Add,null)}}};if(cart.isNotEmpty()){HorizontalDivider();Row(Modifier.fillMaxWidth().padding(top=10.dp),horizontalArrangement=Arrangement.SpaceBetween){Text("TOTAL",fontWeight=FontWeight.Bold);Text(money(cart.sumOf{it.total}),fontWeight=FontWeight.Bold)};Button(onClick=send,Modifier.fillMaxWidth().padding(top=10.dp)){Text("CUSTOMER DETAILS & PRINT KITCHEN")}}}}}}

@Composable
fun ManualCartDialog(menu:List<MenuItem>,add:(MenuItem)->Unit,addCustom:(String,Int,Double)->Unit,close:()->Unit){var query by remember{mutableStateOf("")};var name by remember{mutableStateOf("")};var qty by remember{mutableStateOf("1")};var price by remember{mutableStateOf("")};val filtered=menu.filter{it.name.contains(query,true)||it.variant.contains(query,true)||it.size.contains(query,true)}.sortedBy{it.name};AlertDialog(onDismissRequest=close,title={Text("Add Product")},text={Column(Modifier.fillMaxWidth().heightIn(max=600.dp).verticalScroll(rememberScrollState()),verticalArrangement=Arrangement.spacedBy(8.dp)){OutlinedTextField(query,{query=it},Modifier.fillMaxWidth(),label={Text("Search product / variant")},singleLine=true);filtered.take(30).forEach{item->Card(Modifier.fillMaxWidth().clickable{add(item)}){Row(Modifier.padding(10.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(item.name,fontWeight=FontWeight.SemiBold);Text(listOf(item.variant,item.size).filter(String::isNotBlank).joinToString(" • "));Text(money(item.price))};Icon(Icons.Default.Add,null)}}};HorizontalDivider();Text("Quick custom product",fontWeight=FontWeight.Bold);OutlinedTextField(name,{name=it},label={Text("Product")},modifier=Modifier.fillMaxWidth(),singleLine=true);Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(8.dp)){OutlinedTextField(qty,{qty=it.filter(Char::isDigit)},label={Text("Qty")},modifier=Modifier.weight(1f),singleLine=true);OutlinedTextField(price,{price=it},label={Text("Price")},modifier=Modifier.weight(1f),singleLine=true)};Button(onClick={val q=qty.toIntOrNull()?:0;val p=price.toDoubleOrNull()?:0.0;if(name.isNotBlank()&&q>0&&p>0){addCustom(name.trim(),q,p);name="";price="";qty="1"}},Modifier.fillMaxWidth()){Text("ADD TO ORDER")}}},confirmButton={TextButton(onClick=close){Text("DONE")}})}

@Composable
fun MenuPage(menu:List<MenuItem>,store:Store,refresh:()->Unit,exportMenu:()->Unit,importMenu:()->Unit,scanDocument:()->Unit,addToCart:(MenuItem)->Unit){var adding by remember{mutableStateOf(false)};var editing by remember{mutableStateOf<MenuItem?>(null)};Column(Modifier.fillMaxSize().padding(16.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(6.dp)){Button(onClick={adding=true},Modifier.weight(1f)){Text("ADD")};OutlinedButton(onClick=exportMenu,Modifier.weight(1f)){Text("EXPORT")};OutlinedButton(onClick=importMenu,Modifier.weight(1f)){Text("IMPORT")}};Button(onClick=scanDocument,Modifier.fillMaxWidth()){Icon(Icons.Default.DocumentScanner,null);Spacer(Modifier.width(6.dp));Text("SMART MENU SCANNER — IMAGE / PDF")};Text("Tap a product to add • long management actions below",style=MaterialTheme.typography.bodySmall);LazyColumn{items(menu,key={it.id}){item->Card(Modifier.fillMaxWidth().padding(vertical=3.dp)){Row(Modifier.padding(10.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f).clickable{addToCart(item)}){Text(item.name,fontWeight=FontWeight.SemiBold);Text(listOf(item.variant,item.size).filter(String::isNotBlank).joinToString(" • "));Text(money(item.price))};IconButton(onClick={editng(item).also{editing=item}}){Icon(Icons.Default.Edit,"Edit")};IconButton(onClick={store.removeMenuItem(item.id);refresh()}){Icon(Icons.Default.Delete,"Delete")}}}}}};if(adding)AddMenuDialog({n,v,s,p->store.addMenuItem(MenuItem(System.currentTimeMillis(),n.trim(),p,v.trim(),s.trim()));adding=false;refresh()}){adding=false};editing?.let{item->EditMenuDialog(item,{store.updateMenuItem(it);editing=null;refresh()},{editing=null})}}

private fun editng(item:MenuItem)=Unit

@Composable
fun AddMenuDialog(save:(String,String,String,Double)->Unit,close:()->Unit){var n by remember{mutableStateOf("")};var v by remember{mutableStateOf("")};var s by remember{mutableStateOf("")};var p by remember{mutableStateOf("")};AlertDialog(onDismissRequest=close,title={Text("Add Product")},text={Column(verticalArrangement=Arrangement.spacedBy(6.dp)){OutlinedTextField(n,{n=it},label={Text("Product name")},singleLine=true);OutlinedTextField(v,{v=it},label={Text("Variant — e.g. Regular / Special")},singleLine=true);OutlinedTextField(s,{s=it},label={Text("Size — e.g. Small / Large")},singleLine=true);OutlinedTextField(p,{p=it},label={Text("Price")},singleLine=true)}},confirmButton={TextButton(onClick={p.toDoubleOrNull()?.takeIf{it>0}?.let{if(n.isNotBlank())save(n,v,s,it)}}){Text("SAVE PRODUCT")}},dismissButton={TextButton(onClick=close){Text("CANCEL")}})}

@Composable
fun EditMenuDialog(item:MenuItem,save:(MenuItem)->Unit,close:()->Unit){var n by remember{mutableStateOf(item.name)};var v by remember{mutableStateOf(item.variant)};var s by remember{mutableStateOf(item.size)};var p by remember{mutableStateOf(item.price.toString())};AlertDialog(onDismissRequest=close,title={Text("Edit Product")},text={Column(verticalArrangement=Arrangement.spacedBy(6.dp)){OutlinedTextField(n,{n=it},label={Text("Product")},singleLine=true);OutlinedTextField(v,{v=it},label={Text("Variant")},singleLine=true);OutlinedTextField(s,{s=it},label={Text("Size")},singleLine=true);OutlinedTextField(p,{p=it},label={Text("Price")},singleLine=true)}},confirmButton={TextButton(onClick={p.toDoubleOrNull()?.takeIf{it>=0}?.let{save(item.copy(name=n.trim(),variant=v.trim(),size=s.trim(),price=it))}}){Text("SAVE CHANGES")}},dismissButton={TextButton(onClick=close){Text("CANCEL")}})}

@Composable
fun KitchenQueue(queue:List<PendingSale>,profile:CompanyProfile,printer:PrinterManager,pay:(PendingSale)->Unit,edit:(PendingSale)->Unit){Column(Modifier.fillMaxSize().padding(16.dp)){Text("Kitchen Queue",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);LazyColumn{items(queue,key={it.id}){order->Card(Modifier.fillMaxWidth().padding(vertical=4.dp).clickable{edit(order)}){Row(Modifier.padding(12.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text("#${order.id}",fontWeight=FontWeight.Bold);Text(order.items.joinToString(", "){"${it.qty}× ${it.name}"});if(order.customerName.isNotBlank()||order.customerPhone.isNotBlank())Text(listOf(order.customerName,order.customerPhone).filter(String::isNotBlank).joinToString(" • "))};TextButton(onClick={pay(order)}){Text("PAY & PRINT")}}}}}}}

@Composable
fun EditDialog(order:PendingSale,save:(PendingSale)->Unit,close:()->Unit){var items by remember{mutableStateOf(order.items)};AlertDialog(onDismissRequest=close,title={Text("Edit Order")},text={Column{items.forEach{item->Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Text("${item.qty} × ${item.name}",Modifier.weight(1f));IconButton(onClick={items=items.map{x->if(x==item)x.copy(qty=x.qty-1)else x}.filter{it.qty>0}}){Icon(Icons.Default.Remove,null)};IconButton(onClick={items=items.map{x->if(x==item)x.copy(qty=x.qty+1)else x}}){Icon(Icons.Default.Add,null)}}}}},confirmButton={TextButton(onClick={save(order.copy(items=items))}){Text("SAVE")}},dismissButton={TextButton(onClick=close){Text("CLOSE")}})}

private fun FilterRow(selected:Int,onSelect:(Int)->Unit){Row(Modifier.horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(6.dp)){listOf("Today","7 Days","30 Days","All").forEachIndexed{i,label->FilterChip(selected==i,{onSelect(i)},label={Text(label)})}}

@Composable
fun SalesPage(sales:List<Sale>,open:(Sale)->Unit){var filter by remember{mutableIntStateOf(0)};var query by remember{mutableStateOf("")};val shown=sales.filter{inRange(it.time,filter)}.filter{query.isBlank()||it.id.toString().contains(query)||it.customerName.contains(query,true)||it.customerPhone.contains(query,true)}.sortedByDescending{it.time};Column(Modifier.fillMaxSize().padding(16.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Text("Sales History",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Spacer(Modifier.weight(1f));Text(money(shown.sumOf{it.total}),fontWeight=FontWeight.Bold)};OutlinedTextField(query,{query=it},Modifier.fillMaxWidth(),label={Text("Search receipt / customer / phone")},singleLine=true);FilterRow(filter){filter=it};Text("${shown.size} receipts",style=MaterialTheme.typography.bodySmall);LazyColumn{items(shown,key={it.id}){sale->Card(Modifier.fillMaxWidth().padding(vertical=3.dp).clickable{open(sale)}){Row(Modifier.padding(12.dp)){Column(Modifier.weight(1f)){Text("Receipt #${sale.id}",fontWeight=FontWeight.Bold);if(sale.customerName.isNotBlank()||sale.customerPhone.isNotBlank())Text(listOf(sale.customerName,sale.customerPhone).filter(String::isNotBlank).joinToString(" • "));Text(date(sale.time))};Text(money(sale.total))}}}}}}

@Composable
fun SaleDetailDialog(sale:Sale,profile:CompanyProfile,printer:PrinterManager,theme:ReceiptTheme,close:()->Unit){AlertDialog(onDismissRequest=close,title={Text("Receipt #${sale.id}")},text={Column(Modifier.verticalScroll(rememberScrollState())){Text(date(sale.time),style=MaterialTheme.typography.bodySmall);if(sale.customerName.isNotBlank()||sale.customerPhone.isNotBlank())Text("Customer: "+listOf(sale.customerName,sale.customerPhone).filter(String::isNotBlank).joinToString(" • "),fontWeight=FontWeight.Bold);sale.items.forEach{Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text("${it.qty} × ${it.name}");Text(money(it.total))}};HorizontalDivider();Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text("TOTAL",fontWeight=FontWeight.Bold);Text(money(sale.total),fontWeight=FontWeight.Bold)}}},confirmButton={TextButton(onClick={printer.printCustomer(customerReceipt(sale,profile,theme))}){Text("RE-PRINT RECEIPT")}},dismissButton={TextButton(onClick=close){Text("CLOSE")}})}

@Composable
fun CustomerDetailsDialog(done:(String,String)->Unit,close:()->Unit){var n by remember{mutableStateOf("")};var p by remember{mutableStateOf("")};AlertDialog(onDismissRequest=close,title={Text("Customer Details")},text={Column(verticalArrangement=Arrangement.spacedBy(8.dp)){OutlinedTextField(n,{n=it},label={Text("Customer Name")},singleLine=true);OutlinedTextField(p,{p=it},label={Text("Phone")},singleLine=true)}},confirmButton={TextButton(onClick={done(n,p)}){Text("PRINT KITCHEN")}},dismissButton={TextButton(onClick=close){Text("SKIP")}})}

@Composable
fun ExpensesPage(expenses:List<Expense>,add:()->Unit,profile:CompanyProfile,printer:PrinterManager,theme:ReceiptTheme,refresh:()->Unit){var filter by remember{mutableIntStateOf(0)};var selected by remember{mutableStateOf<Expense?>(null)};val shown=expenses.filter{inRange(it.time,filter)}.sortedByDescending{it.time};Column(Modifier.fillMaxSize().padding(16.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Text("Expenses",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Spacer(Modifier.weight(1f));Button(onClick=add){Text("ADD")}};FilterRow(filter){filter=it};Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text("${shown.size} expenses");Text("TOTAL ${money(shown.sumOf{it.amount})}",fontWeight=FontWeight.Bold)};LazyColumn{items(shown,key={it.id}){e->Card(Modifier.fillMaxWidth().padding(vertical=3.dp).clickable{selected=e}){ListItem(headlineContent={Text(e.title,fontWeight=FontWeight.SemiBold)},supportingContent={Text("${e.category} • ${date(e.time)}")},trailingContent={Text(money(e.amount),fontWeight=FontWeight.Bold)})}}}};selected?.let{e->ExpenseDetailDialog(e,profile,printer,theme,{selected=null},{refresh();selected=null})}}

@Composable
fun ExpenseDetailDialog(e:Expense,profile:CompanyProfile,printer:PrinterManager,theme:ReceiptTheme,close:()->Unit,changed:()->Unit){AlertDialog(onDismissRequest=close,title={Text("Expense #${e.id}")},text={Column(verticalArrangement=Arrangement.spacedBy(5.dp)){Text(e.title,fontWeight=FontWeight.Bold);Text(e.category);Text(date(e.time));Text(money(e.amount),style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold)}},confirmButton={TextButton(onClick={printer.printCustomer(expenseReceipt(e,profile,theme))}){Text("PRINT EXPENSE")}},dismissButton={TextButton(onClick=close){Text("CLOSE")}})}

@Composable
fun Analytics(sales:List<Sale>,expenses:List<Expense>,cash:Double){var filter by remember{mutableIntStateOf(0)};val ss=sales.filter{inRange(it.time,filter)};val es=expenses.filter{inRange(it.time,filter)};val sv=ss.sumOf{it.total};val ev=es.sumOf{it.amount};Column(Modifier.fillMaxSize().padding(16.dp).verticalScroll(rememberScrollState()),verticalArrangement=Arrangement.spacedBy(6.dp)){Text("Business Analysis",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);FilterRow(filter) {filter=it};Metric("Sales",sv,Icons.Default.TrendingUp);Metric("Expenses",ev,Icons.Default.TrendingDown);Metric("Net",sv-ev,Icons.Default.AccountBalance);Metric("Current Cash",cash,Icons.Default.AccountBalanceWallet);Text("${ss.size} sales • ${es.size} expenses",style=MaterialTheme.typography.bodySmall);HorizontalDivider();Text("Top Products",fontWeight=FontWeight.Bold);ss.flatMap{it.items}.groupBy{it.name}.mapValues{it.value.sumOf{x->x.qty}}.entries.sortedByDescending{it.value}.take(10).forEach{Row(Modifier.fillMaxWidth().padding(5.dp),horizontalArrangement=Arrangement.SpaceBetween){Text(it.key);Text("${it.value} sold")}}}}
@Composable fun Metric(title:String,value:Double,icon:ImageVector){Card(Modifier.fillMaxWidth().padding(vertical=2.dp)){Row(Modifier.padding(14.dp),verticalAlignment=Alignment.CenterVertically){Icon(icon,null);Text(title,Modifier.weight(1f));Text(money(value),fontWeight=FontWeight.Bold)}}}
@Composable fun EmptyState(icon:ImageVector,title:String,body:String){Column(Modifier.fillMaxWidth().padding(24.dp),horizontalAlignment=Alignment.CenterHorizontally){Icon(icon,null);Text(title,fontWeight=FontWeight.Bold);Text(body)}}
@Composable fun OpeningCash(done:(Double)->Unit){var v by remember{mutableStateOf("")};AlertDialog(onDismissRequest={},title={Text("Opening Cash")},text={OutlinedTextField(v,{v=it},label={Text("Cash")})},confirmButton={TextButton(onClick={done(v.toDoubleOrNull()?:0.0)}){Text("CONTINUE")}})}
@Composable fun ExpenseDialog(done:(String,String,Double)->Unit){var n by remember{mutableStateOf("")};var c by remember{mutableStateOf("")};var a by remember{mutableStateOf("")};AlertDialog(onDismissRequest={},title={Text("Expense")},text={Column(verticalArrangement=Arrangement.spacedBy(6.dp)){OutlinedTextField(n,{n=it},label={Text("Description")});OutlinedTextField(c,{c=it},label={Text("Category")});OutlinedTextField(a,{a=it},label={Text("Amount")})}},confirmButton={TextButton(onClick={a.toDoubleOrNull()?.takeIf{it>0}?.let{done(n,c,it)}}){Text("SAVE EXPENSE")}})}

@Composable fun SettingsPage(store:Store,printer:PrinterManager,pickLogo:()->Unit,exportBackup:()->Unit,importBackup:()->Unit,close:()->Unit){var profile by remember{mutableStateOf(store.profile())};var theme by remember{mutableStateOf(store.theme())};AlertDialog(onDismissRequest=close,title={Text("Settings")},text={Column(Modifier.verticalScroll(rememberScrollState()),verticalArrangement=Arrangement.spacedBy(8.dp)){Text("Business Transfer",fontWeight=FontWeight.Bold);Row(Modifier.fillMaxWidth()){Button(onClick=exportBackup,Modifier.weight(1f)){Text("EXPORT")};OutlinedButton(onClick=importBackup,Modifier.weight(1f)){Text("IMPORT")}};OutlinedTextField(profile.name,{profile=profile.copy(name=it)},label={Text("Company Name")});OutlinedTextField(profile.phone,{profile=profile.copy(phone=it)},label={Text("Phone")});OutlinedTextField(profile.address,{profile=profile.copy(address=it)},label={Text("Address")},minLines=3);OutlinedTextField(profile.footer,{profile=profile.copy(footer=it)},label={Text("Footer")});Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Text(if(profile.logoPath.isNotBlank())"Company logo saved ✓" else "Company logo not uploaded",Modifier.weight(1f));OutlinedButton(onClick=pickLogo){Text("UPLOAD / CHANGE LOGO")}};Text("Receipt style");Row(Modifier.horizontalScroll(rememberScrollState())){ReceiptTheme.values().forEach{t->FilterChip(theme==t,{theme=t},label={Text(t.name)})}};Text("Printer, Tax & Currency are available from the top bar.",style=MaterialTheme.typography.bodySmall)}},confirmButton={TextButton(onClick={store.saveProfile(profile.copy(saleLogoEnabled=true,kitchenLogoEnabled=true));store.setTheme(theme);close()}){Text("SAVE")}})}
