package com.findupto.voicepos

import android.graphics.Bitmap
import android.graphics.BitmapFactory
import java.io.ByteArrayOutputStream
import java.text.SimpleDateFormat
import java.util.*

fun money(v:Double)="${CurrencySettings.symbol} "+String.format(Locale.US,"%,.0f",v)
fun date(v:Long)=SimpleDateFormat("dd MMM yyyy, hh:mm a",Locale.US).format(Date(v))
private const val W=42
private const val SEP="------------------------------------------"
private fun fit(s:String,n:Int)=s.replace("\n"," ").trim().take(n)
private fun pair(a:String,b:String):String{val r=fit(b,W);val l=fit(a,W-r.length-1);return l+" ".repeat((W-l.length-r.length).coerceAtLeast(1))+r}
private fun cols(name:String,qty:String,price:String):String{val pw=11;val qw=6;val nw=W-qw-pw-2;return fit(name,nw).padEnd(nw)+" "+fit(qty,qw).padStart(qw)+" "+fit(price,pw).padStart(pw)}
private fun logo(path:String):ByteArray?{val src=runCatching{BitmapFactory.decodeFile(path)}.getOrNull()?:return null;val maxW=320;val maxH=120;val scale=minOf(1f,maxW.toFloat()/src.width,maxH.toFloat()/src.height);val bmp=if(scale<1)Bitmap.createScaledBitmap(src,(src.width*scale).toInt().coerceAtLeast(8),(src.height*scale).toInt().coerceAtLeast(8),true)else src;val wb=(bmp.width+7)/8;val out=ByteArrayOutputStream();out.write(byteArrayOf(0x1D,0x76,0x30,0,wb.toByte(),(wb shr 8).toByte(),bmp.height.toByte(),(bmp.height shr 8).toByte()));for(y in 0 until bmp.height)for(q in 0 until wb){var v=0;for(bit in 0..7){val x=q*8+bit;if(x<bmp.width){val c=bmp.getPixel(x,y);val g=(android.graphics.Color.red(c)*299+android.graphics.Color.green(c)*587+android.graphics.Color.blue(c)*114)/1000;if(g<205)v=v or(1 shl(7-bit))}};out.write(v)};return out.toByteArray()}
private fun writeHeader(p:CompanyProfile,o:ByteArrayOutputStream,time:Long,kitchen:Boolean=false){fun w(s:String){o.write(s.toByteArray(Charsets.UTF_8))};fun c(vararg x:Int){o.write(x.map{(it and 255).toByte()}.toByteArray())};c(0x1B,0x40,0x1B,0x61,1);val logoAllowed=if(kitchen)p.kitchenLogoEnabled else p.saleLogoEnabled;if(logoAllowed&&p.logoPath.isNotBlank())logo(p.logoPath)?.let{o.write(it);w("\n")};c(0x1B,0x45,1,0x1D,0x21,0x11);w(fit(p.name.ifBlank{"VOICE POS"},W)+"\n");c(0x1D,0x21,0,0x1B,0x45,0);if(p.phone.isNotBlank())w(fit(p.phone,W)+"\n");p.address.split("\n").filter{it.isNotBlank()}.forEach{w(fit(it,W)+"\n")};w(SEP+"\n");w(pair("Date",date(time))+"\n")}
private fun escpos(p:CompanyProfile,title:String,items:List<SaleItem>,total:Double,theme:ReceiptTheme,customerName:String="",customerPhone:String="",time:Long=System.currentTimeMillis(),orderType:String="DINE_IN",customerAddress:String="",paymentMethod:String="",paidAmount:Double=total,dueAmount:Double=0.0):ByteArray{val o=ByteArrayOutputStream();fun w(s:String){o.write(s.toByteArray(Charsets.UTF_8))};fun c(vararg x:Int){o.write(x.map{(it and 255).toByte()}.toByteArray())};val subtotal=items.sumOf{it.total};val service=if(p.serviceChargeEnabled)subtotal*p.serviceChargeRate/100.0 else 0.0;val taxBase=subtotal+service;val tax=if(p.taxEnabled)taxBase*p.taxRate/100.0 else 0.0;writeHeader(p,o,time);c(0x1B,0x45,1);w(fit(title,W)+"\n");c(0x1B,0x45,0);w(pair("Order Type",orderType.replace('_',' '))+"\n");if(customerName.isNotBlank()||customerPhone.isNotBlank()||customerAddress.isNotBlank()){w(SEP+"\n");if(customerName.isNotBlank()||customerPhone.isNotBlank())w(pair(customerName.ifBlank{"Customer"},customerPhone)+"\n");if(customerAddress.isNotBlank())w("Address: "+fit(customerAddress,W-9)+"\n")};w(SEP+"\n");w(cols("ITEM","QTY","PRICE")+"\n");w(SEP+"\n");items.forEach{w(cols(it.name,it.qty.toString(),money(it.total))+"\n")};w(SEP+"\n");w(pair("Bill",money(subtotal))+"\n");if(p.serviceChargeEnabled&&service>0)w(pair(p.serviceChargeLabel.ifBlank{"Service Charge"}+" ${p.serviceChargeRate}%",money(service))+"\n");if(p.taxEnabled&&tax>0)w(pair(p.taxLabel.ifBlank{"Tax"}+" ${p.taxRate}%",money(tax))+"\n");c(0x1B,0x45,1);w(pair("TOTAL BILL",money(total))+"\n");c(0x1B,0x45,0);if(paymentMethod.isNotBlank())w(pair("Paid via",paymentMethod)+"\n");if(dueAmount>0.005){w(pair("Paid",money(paidAmount))+"\n");w(pair("BALANCE DUE",money(dueAmount))+"\n")};w(SEP+"\n");if(p.footer.isNotBlank()){c(0x1B,0x61,1);w(fit(p.footer,W)+"\n")};w("\n\n\n");return o.toByteArray()}
fun customerReceipt(s:Sale,p:CompanyProfile,t:ReceiptTheme)=escpos(p,"SALE #"+s.id,s.items,s.total,t,s.customerName,s.customerPhone,s.time,s.orderType,s.customerAddress,s.paymentMethod,s.paidAmount,s.dueAmount)
fun expenseReceipt(e:Expense,p:CompanyProfile,t:ReceiptTheme):ByteArray{val o=ByteArrayOutputStream();fun w(s:String){o.write(s.toByteArray(Charsets.UTF_8))};fun c(vararg x:Int){o.write(x.map{(it and 255).toByte()}.toByteArray())};writeHeader(p,o,e.time);c(0x1B,0x45,1);w("EXPENSE #${e.id}\n");c(0x1B,0x45,0);w(SEP+"\n");w(pair("Description",e.title)+"\n");w(pair("Category",e.category)+"\n");w(pair("Paid via",e.paymentMethod)+"\n");w(SEP+"\n");c(0x1B,0x45,1);w(pair("AMOUNT",money(e.amount))+"\n");c(0x1B,0x45,0);w(SEP+"\n");if(p.footer.isNotBlank())w(fit(p.footer,W)+"\n");w("\n\n\n");return o.toByteArray()}
fun kitchenReceipt(s:PendingSale,p:CompanyProfile,t:ReceiptTheme):ByteArray{val o=ByteArrayOutputStream();fun w(x:String){o.write(x.toByteArray(Charsets.UTF_8))};fun c(vararg x:Int){o.write(x.map{(it and 255).toByteArray()}.flatMap{it.toList()}.toByteArray())};writeHeader(p,o,s.time,true);c(0x1B,0x45,1,0x1D,0x21,0x11);w("KITCHEN ORDER\n");c(0x1D,0x21,0,0x1B,0x45,0);w(pair("ORDER #"+s.id,date(s.time))+"\n");c(0x1B,0x45,1);w(pair("TYPE",s.orderType.replace('_',' '))+"\n");c(0x1B,0x45,0);if(s.customerName.isNotBlank()||s.customerPhone.isNotBlank())w(pair(s.customerName.ifBlank{"Customer"},s.customerPhone)+"\n");if(s.customerAddress.isNotBlank()){w(SEP+"\n");w("DELIVERY ADDRESS\n");w(fit(s.customerAddress,W)+"\n")};w(SEP+"\n");s.items.forEach{w(pair(it.qty.toString()+" ×",it.name)+"\n")};w(SEP+"\n");if(s.orderType.equals("DELIVERY",true))w("*** DELIVERY — GIVE TO RIDER ***\n");if(s.orderType.equals("TAKEAWAY",true))w("*** TAKEAWAY ***\n");w("\n\n\n");return o.toByteArray()}
fun startDay():Long=Calendar.getInstance().apply{set(Calendar.HOUR_OF_DAY,0);set(Calendar.MINUTE,0);set(Calendar.SECOND,0);set(Calendar.MILLISECOND,0)}.timeInMillis
fun inRange(t:Long,f:Int):Boolean{val since=when(f){0->startDay();1->System.currentTimeMillis()-7*86400000L;2->System.currentTimeMillis()-30*86400000L;else->0L};return t>=since}
